version: '3'
services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    ports:
      - "9092:9092"

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports: ["8086:8086"]
    environment:
      - INFLUXDB_DB=crypto_project

  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports: ["3000:3000"]
    depends_on: [influxdb]

  
  minio:
    image: minio/minio
    container_name: minio
    ports: ["9000:9000", "9001:9001"]
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"

  
  trino:
    image: trinodb/trino:latest
    container_name: trino
    ports: ["8080:8080"]
    volumes:
      - ./trino/catalog:/etc/trino/catalog
    depends_on: [minio]