connector.name=delta
# On utilise MinIO comme S3
fs.native-s3.enabled=true
s3.endpoint=http://minio:9000
s3.path-style-access=true
s3.access-key=admin
s3.secret-key=password
# Configuration simple sans Metastore complexe (File-Based)
hive.metastore=file
hive.metastore.catalog.dir=/etc/trino/catalog/